### ISSUE TITLE
Write `customManagers` entry to update `renovateVersion` string in Markdown files

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/.github#596]
We want to get updates from Renovate bot for the `renovateVersion` string in the FAQ Markdown file.

### How?

`@rarkins` proposed:

> I think that using npm or Docker versions as "close enough" is good enough for us. We won't want to update this all the time either, e.g. we could update this monthly like we do with renovate versions in other docs.

Source:

- https://github.com/renovatebot/renovate/pull/32054#issuecomment-2434658591

### Todos

I don't know enough to write the new Renovate configuration. I hope someone smart at regex can help! Here are the todos:

Write new config code in [`default.json`](https://github.com/renovatebot/.github/blob/main/default.json):

- [ ] Write a new `customManagers` entry, to update the `"renovateVersion": "38.120.1"` pattern string in Markdown files.
- [ ] Use the version of Renovate from npm, or Docker as "close enough" approximation of the version of the Mend hosted Renovate app.
- [ ] Set the schedule to monthly (or match the schedule for the other Markdown docs updates).

**Comment by viceice** [comment]
i think this simply needs another regex added here:
https://github.com/renovatebot/.github/blob/bf45bb3cc9b96de46a437bd4d03820ca71ac1241/default.json#L140-L151
